services:
   itm.image.preview.form_image_type:
       class: ITM\ImagePreviewBundle\Form\Type\ImagePreviewType
       arguments: ['@service_container']
       tags:
           - { name: form.type, alias: itm_image_preview }

   itm.image.preview.twig_extension:
       class: ITM\ImagePreviewBundle\Twig\Extension\ImagePreviewExtension
       arguments: ['@itm.file.preview.path.resolver', '@service_container']
       tags:
           - { name: twig.extension }
